sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anshul495/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anshul495/docker-react npm run test